In [11]:
import numpy as np
from numpy import random 
x=random.randint(low=1,high=11,size=(3,3))      
y=random.randint(low=1,high=11,size=(3,3)) 
print(x)
print(y)

[[3 8 9]
 [9 8 3]
 [8 9 7]]
[[7 4 9]
 [7 8 9]
 [2 8 2]]


In [12]:
print(x+y)

[[10 12 18]
 [16 16 12]
 [10 17  9]]


In [13]:
print(x*y)

[[21 32 81]
 [63 64 27]
 [16 72 14]]


In [14]:
print(x@y)

[[ 95 148 117]
 [125 124 159]
 [133 160 167]]


In [15]:
print(np.linalg.det(x))

-72.0
